[package]
name = "pdf_render_flutter"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = "2.7"
pdf_render = { git="https://github.com/videni/pdf_render_with_vello.git", branch="vello_wip"}